### ISSUE TITLE
This is my theme

### ISSUE THREAD

**Issue by manouel-1** [Zircon-Dev/Faliactyl-Soft-Ui-Theme#1]
Did you get my premision to upload this theme this is mine you even changed credits

**Comment by KingTino104** [comment]
send link

**Comment by manouel-1** [comment]
in my old account and its delete but i can sent someones else that have forked it before i deleted my acc

**Comment by KingTino104** [comment]
ok send that then

**Comment by manouel-1** [comment]
![image](https://user-images.githubusercontent.com/101193668/196708608-6342d9d9-7b8f-4a2c-acc9-5f9b2c660e5b.png)
https://github.com/rjlad/dashactyl-soft-ui-theme
see same things different creds

**Comment by KingTino104** [comment]
ok
